### ISSUE TITLE
Stress UDP

### ISSUE THREAD

**Issue by k3v1n01** [fredericopissarra/t50#10]
Boa Tarde Frederico,

Estou testando alguns parâmetros e com um tcpdump no meu dedicado monitorando o comportamento do T50. Porem já testei vários parâmetros e a aplicação parece não sofrer nem uma alteração, caso eu teste com um hping3 ou g3m posso ver uma variação de desempenho muito grande, estou fazendo algo errado? 
O meu objetivo é stress ao máximo uma porta especifica utilizando o protocolo UDP, se possível utilizando spoofing na origem do ataque, para que eu possa monitorar o funcionamento do dedicado e diferentes tratativas no iptables.

root@srv051214:~/t50/release# ./t50 --flood --turbo --dport 7171,7172 --protocol UDP <Minha Dedicada>
Entering in flood mode...
Activating turbo...
Performing DDoS...
Hit CTRL+C to break.
T50 5.5 successfully launched at Mar 31st 2015 22:41:04

Atenciosamente,
Kevin.

**Comment by kl0nez** [comment]
Olá Kevin,

Percebí que você está passando 2 portas como parâmetro, teste com somente uma porta. Também não ví na sua linha de comando do exemplo, o IP para o destino dos pacotes.

Como "aparentemente" você está utilizando um ambiente controlado, verifique no destino se os pacotes estão chegando, algo como:

$ sudo tcpdump -n -i eth0 port 7171 or port 7172

Assim você vai verificar se a sua execução está gerando os fluxos desejados e se os mesmos estão chegando ao destino.

sds
Kl0nEz

**Comment by fredericopissarra** [comment]
Kevin,

kl0nez respondeu sua dúvida e, como conversamos antes, fiz o debugging do T50 e constatei que os pacotes estão sendo montados e enviados corretamente. Possivelmente há alguma filtragem ocorrendo em sua estrutura de rede.

[]s
Fred

**Comment by k3v1n01** [comment]
Bom dia Senhores,

Também efetuei os mesmo testes em rede local e realmente o T50 envia os pacotes corretamente.
Porem quando falamos em redes EXTERNAS ele não esta enviando, efetuei os testes em 3 dedicados diferentes, sem nem um tipo de firewall ou bloqueio. Não é possível que em três endereços diferentes tenha algum tipo de filtragem ocorrendo, não consigo entender.

Analisando pacotes com TCPDUMP: Dedicado 01
tcpdump -i eth0 'port 7171'

Enviando Stress: Dedicado 02
./t50 --turbo --flood --protocol UDP --dport 7171 157.7.120.241

**Comment by kl0nez** [comment]
Bom dia Kevin,

No tcpdump feito na estação que você está executando o T50, você consegue
"ver" o fluxo saindo ? Existem ACLs na estação ? Teste sem o "--turbo
--flood", só para termos certeza de que os pacotes estão sendo enviados.

Estou tentando validar os seguintes estágios:

1 - Certificar de que os pacotes estão sendo construídos; (com a nova opção
e debug, vc consegue ver)
2 - Certificar de que os pacotes estão sendo enviados; (tcpdump na sua
estação)
3 - Certificar de que os pacotes chegaram na rede; (tcpdump na sua rede, ou
em um destino no mesmo segmento e conhecido)
4 - Certificar de que os pacotes saíram da sua rede; (tcpdump em uma
máquina fora da sua rede, mas que você tenha controle)

Daí pra frente, já não temos muito controle, por exemplo, se na borda da
rede onde você está, há alguma filtragem, destinos externos podem não
receber os pacotes (apesar dos mesmos terem saído da sua estação). Porém,
não conheço a sua infra para sugerir estas hipoteses, daí qualquer coisa
que eu disser pode estar muito errada :) .

Obs.: como o T50 vai enviar muitos pacotes (esperamos né), opte por usar a
flag "-n" no tcpdump, para evitar sobrecarga na estrutura de DNS.

sds
Kl0nEz

Em 8 de abril de 2015 11:35, Kevin <notifications@github.com> escreveu:
