### ISSUE TITLE
Executable not visible

### ISSUE THREAD

**Issue by jrmatos** [fredericopissarra/t50#11]
I just download, extracted and ran 'make -W Makefile'. After it when I run 'ls' I just get these files/directories:

build  CHANGELOG  doc  LICENSE  Makefile  README  release  src  TODO

The executable is not visible. The compilation was successful. Am I doing something wrong? 

Thanks.

**Comment by merces** [comment]
If compilation was successful, you should have seen something similar to this in the last line of make output:

    cc -o release/t50 build/modules/ip.o build/modules/igmpv3.o build/modules/dccp.o build/modules/ripv2.o build/modules/udp.o build/modules/tcp.o build/modules/ospf.o build/modules/ripv1.o build/modules/egp.o build/modules/rsvp.o build/modules/ipsec.o build/modules/eigrp.o build/modules/gre.o build/modules/igmpv1.o build/modules/icmp.o build/common.o build/cksum.o build/cidr.o build/t50.o build/resolv.o build/sock.o build/usage.o build/config.o build/modules.o build/help/general_help.o build/help/gre_help.o build/help/tcp_udp_dccp_help.o build/help/ip_help.o build/help/icmp_help.o build/help/egp_help.o build/help/rip_help.o build/help/rsvp_help.o build/help/ipsec_help.o build/help/eigrp_help.o build/help/ospf_help.o  -s -O3 -fuse-linker-plugin -flto

That means, the binary will be under 'release' directory. ;)
