### ISSUE TITLE
Buggy parser

### ISSUE THREAD

**Issue by MarcosFouces** [fredericopissarra/t50#16]
Hello Frederico

The bug in the parser you wanted to fix with this new release (5.6.4) is newly present.

¿Could you make a new release with the correct fix?

Thank you very much.

**Comment by fredericopissarra** [comment]
This "bug" is still present on release 5.6.7-fix1?
If so, I'll need some examples...

**Comment by MarcosFouces** [comment]
Try the man page example:
root@debian# t50 --flood 192.168.0.100
t50: Option '--flood' has no arguments.

If you want to run it properly, you need to execute this one instead:

root@debian:# t50 192.168.0.100 --flood
Entering flood mode...
Performing stress testing...


I am running 5.6.8 release on Debian Testing. 
Thanks.

**Comment by fredericopissarra** [comment]
Ahhh... yes! This is well known since I rewrote que parser.
Try to use -- before the IP:
`
$ t50 --flood -- 192.168.0.100`

**Comment by fredericopissarra** [comment]
As noted before, the -- pseudo option was created to deal with this issue since I rewrote the command line parser.
