### ISSUE TITLE
Need some example commands to run t50 

### ISSUE THREAD

**Issue by iamfarooqh** [fredericopissarra/t50#19]
Hello there,
Greetings. I've come to know that t50 is the best opensource tool to simulate the DOS and DDoS scenarios. I have seen the man page and t50 --help output but I wasn't able to interpret how I run the tool directly. For that, I  need an example command line syntax to run the tool especially for the TCP and UDP ports. Can you guys please help. Or maybe you can put up some example commands in the README file on github project.

Appreciate your help!

Best
Farooq

**Comment by samueloph** [comment]
The t50 manpage is pretty poor, it definitely needs some love, the help output (--help) has more info but still lacks a better explanation and entries like --protocol (for TCP vs UDP, which is what you want).

Having a wider set o examples on the manpage would be awesome too.

I think the main thing here is: we just need someone to step ahead and prepare a PR, i'm pretty sure upstream would be happy.

I will see if i can get help on the debian side (i'm one of the maintainers of t50 on debian).

For now, until we have a better manpage/--help, i suggest you to search online for examples of t50 usage, there's plenty of it which shows various use cases.

**Comment by fredericopissarra** [comment]
Yes, I agree. The manpage is not that good. But, in version 5.6.13 I tried to made it a bit more enlightening inserting simple examples of usage.

t50 --help will showyou ALL the options and their defaults.

I will be glad to review and change the manpage if someone would be kind enough to do a better job.

**Comment by iamfarooqh** [comment]
Thanks **fredericopissarra** and **samueloph**. I ll share my experience with the 5.6.13 update help option.
