### ISSUE TITLE
Source IP is reversed

### ISSUE THREAD

**Issue by vx69224** [fredericopissarra/t50#23]
Hi,
I'm using "-s <source ip>" flag. It seems that source IP written in reverse to the packet (a.b.c.d shows as d.c.b.a) in the connection.
Thanks,

**Comment by juliourena** [comment]
I was thinking it was using a Random value, but as I tested now if I write 4.1.168.192 it currently send the packet with the IP 192.168.1.4. 

Thanks! Hope you can fix it

**Comment by fredericopissarra** [comment]
Thanks, I'll take a look...

**Comment by fredericopissarra** [comment]
Please, get the last revision on master branch, recompile it and test if everything is ok. If so, I'll release it.

**Comment by fredericopissarra** [comment]
I think I got it right on release 5.7.0 now... thanks a lot!
