### ISSUE TITLE
build issue - deps missing? 

### ISSUE THREAD

**Issue by alphaaurigae** [fredericopissarra/t50#24]
Making uninstall in src
make[1]: Entering directory '/opt/ITSEC/10.Stresstest/t50/fredericopissarra/t50/src'
 ( cd '/usr/local/sbin' && rm -f t50 )
make[1]: Leaving directory '/opt/ITSEC/10.Stresstest/t50/fredericopissarra/t50/src'
Making uninstall in .
make[1]: Entering directory '/opt/ITSEC/10.Stresstest/t50/fredericopissarra/t50'
 ( cd '/usr/local/share/man/man8' && rm -f t50.8 )
make[1]: Leaving directory '/opt/ITSEC/10.Stresstest/t50/fredericopissarra/t50'
Removing Makefile
Removing config.log
Removing config.status
Removing src/Makefile
Removing src/config.o
Removing src/help/.dirstamp
Removing src/include/configuration.h
Removing src/include/stamp-h1
Removing src/main.o
Removing src/modules.o
Removing src/modules/.dirstamp
Removing src/usage.o
Already up-to-date.
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking whether gcc and cc understand -c and -o together... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for preprocessor stringizing operator... yes
checking for __attribute__... yes
checking whether C compiler accepts -std=gnu11... yes
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking arpa/inet.h usability... yes
checking arpa/inet.h presence... yes
checking for arpa/inet.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking for inttypes.h... (cached) yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking netdb.h usability... yes
checking netdb.h presence... yes
checking for netdb.h... yes
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking stddef.h usability... yes
checking stddef.h presence... yes
checking for stddef.h... yes
checking for stdint.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking for unistd.h... (cached) yes
checking for stdbool.h that conforms to C99... yes
checking for _Bool... yes
checking for pid_t... yes
checking for size_t... yes
checking for uint64_t... yes
checking for uint8_t... yes
checking for uint16_t... yes
checking for uint32_t... yes
checking for uint64_t... (cached) yes
checking for error_at_line... yes
checking vfork.h usability... no
checking vfork.h presence... no
checking for vfork.h... no
checking for fork... yes
checking for vfork... yes
checking for working fork... yes
checking for working vfork... (cached) yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible realloc... yes
checking for alarm... yes
checking for regcomp... yes
checking for socket... yes
checking for strcasecmp... yes
checking for strchr... yes
checking for strdup... yes
checking for strerror... yes
checking for strpbrk... yes
checking for strtoul... yes
checking for inline... inline
checking for C/C++ restrict keyword... __restrict
checking for preprocessor stringizing operator... (cached) yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating src/include/configuration.h
config.status: executing depfiles commands
Making all in src
make[1]: Entering directory '/opt/ITSEC/10.Stresstest/t50/fredericopissarra/t50/src'
depbase=`echo main.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I. -I../src/include    -std=gnu11 -O2 -march=native -s -DNDEBUG -fno-stack-protector -MT main.o -MD -MP -MF $depbase.Tpo -c -o main.o main.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo config.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I. -I../src/include    -std=gnu11 -O2 -march=native -s -DNDEBUG -fno-stack-protector -MT config.o -MD -MP -MF $depbase.Tpo -c -o config.o config.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo randomizer.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I. -I../src/include    -std=gnu11 -O2 -march=native -s -DNDEBUG -fno-stack-protector -MT randomizer.o -MD -MP -MF $depbase.Tpo -c -o randomizer.o randomizer.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo usage.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I. -I../src/include    -std=gnu11 -O2 -march=native -s -DNDEBUG -fno-stack-protector -MT usage.o -MD -MP -MF $depbase.Tpo -c -o usage.o usage.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo modules.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I. -I../src/include    -std=gnu11 -O2 -march=native -s -DNDEBUG -fno-stack-protector -MT modules.o -MD -MP -MF $depbase.Tpo -c -o modules.o modules.c &&\
mv -f $depbase.Tpo $depbase.Po
randomizer.c: Assembler messages:
randomizer.c:82: Error: operand size mismatch for `rdrand'
Makefile:523: recipe for target 'randomizer.o' failed
make[1]: *** [randomizer.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/opt/ITSEC/10.Stresstest/t50/fredericopissarra/t50/src'
Makefile:436: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
Making install in src
make[1]: Entering directory '/opt/ITSEC/10.Stresstest/t50/fredericopissarra/t50/src'
depbase=`echo modules/ipsec.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I. -I../src/include    -std=gnu11 -O2 -march=native -s -DNDEBUG -fno-stack-protector -MT modules/ipsec.o -MD -MP -MF $depbase.Tpo -c -o modules/ipsec.o modules/ipsec.c &&\
mv -f $depbase.Tpo $depbase.Po
modules/ipsec.c: In function ‘ipsec’:
modules/ipsec.c:109:3: warning: implicit declaration of function ‘_Generic’ [-Wimplicit-function-declaration]
modules/ipsec.c:109:22: error: expected expression before ‘_Bool’
modules/ipsec.c:110:22: error: expected expression before ‘_Bool’
modules/ipsec.c:120:20: error: expected expression before ‘_Bool’
modules/ipsec.c:121:20: error: expected expression before ‘_Bool’
Makefile:523: recipe for target 'modules/ipsec.o' failed
make[1]: *** [modules/ipsec.o] Error 1
make[1]: Leaving directory '/opt/ITSEC/10.Stresstest/t50/fredericopissarra/t50/src'
Makefile:436: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1

**Comment by fredericopissarra** [comment]
What is your machine's configuration and GCC version?
amd64 or i686?
GCC >= 4.9?

**Comment by fredericopissarra** [comment]
And your processor? What is it?

**Comment by fredericopissarra** [comment]
Seems your compiler does not support ISO 9899:2011 (C11) and RDRAND assembly instruction.
My tests indicate that the Makefile is correct and working properly (for GCC 4.8 or superior).
