### ISSUE TITLE
Error during sudo make install

### ISSUE THREAD

**Issue by Geosex** [fredericopissarra/t50#26]
Hello ,

During installation I face the following error:

config.status: executing depfiles commands
Making all in src
make[1]: Entering directory `/etc/t50/src'
depbase=`echo modules/ipsec.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I. -I../src/include    -O2 -s -DNDEBUG -fno-stack-protector -march=native -std=gnu11 -g -O2 -MT modules/ipsec.o -MD -MP -MF $depbase.Tpo -c -o modules/ipsec.o modules/ipsec.c &&\
mv -f $depbase.Tpo $depbase.Po
modules/ipsec.c: In function \u2018ipsec\u2019:
modules/ipsec.c:109:3: warning: implicit declaration of function \u2018_Generic\u2019 [-Wimplicit-function-declaration]
   ip_auth->spi     = __RND(co->ipsec.ah_spi);
   ^
In file included from modules/ipsec.c:29:0:
../src/include/t50_randomizer.h:18:3: error: expected expression before \u2018_Bool\u2019
   _Bool: (!!(v) ? (v) : RANDOM()),           \
   ^
modules/ipsec.c:109:22: note: in expansion of macro \u2018__RND\u2019
   ip_auth->spi     = __RND(co->ipsec.ah_spi);
                      ^
../src/include/t50_randomizer.h:18:3: error: expected expression before \u2018_Bool\u2019
   _Bool: (!!(v) ? (v) : RANDOM()),           \
   ^
modules/ipsec.c:110:22: note: in expansion of macro \u2018__RND\u2019
   ip_auth->seq_no  = __RND(co->ipsec.ah_sequence);
                      ^
../src/include/t50_randomizer.h:18:3: error: expected expression before \u2018_Bool\u2019
   _Bool: (!!(v) ? (v) : RANDOM()),           \
   ^
modules/ipsec.c:120:20: note: in expansion of macro \u2018__RND\u2019
   ip_esp->spi    = __RND(co->ipsec.esp_spi);
                    ^
../src/include/t50_randomizer.h:18:3: error: expected expression before \u2018_Bool\u2019
   _Bool: (!!(v) ? (v) : RANDOM()),           \
   ^
modules/ipsec.c:121:20: note: in expansion of macro \u2018__RND\u2019
   ip_esp->seq_no = __RND(co->ipsec.esp_sequence);
                    ^
make[1]: *** [modules/ipsec.o] Error 1
make[1]: Leaving directory `/etc/t50/src'
make: *** [all-recursive] Error 1

Thank you ,
George

**Comment by fredericopissarra** [comment]
Please, get the latest release or the latest update from this repository.
I can't reproduce this error and I'm pretty sure there is no U+2018 UTF-8 char in the entire core outside the comments.
