### ISSUE TITLE
TCP Rserved and Nounce are set to 1

### ISSUE THREAD

**Issue by azizhamad** [fredericopissarra/t50#27]
Hello,
i am using this line below:

# t50 192.168.1.1 -s 192.168.1.100 --flood --turbo --syn --dport 179 --md5-signature --protocol tcp

The problem is that: using wireshark i can see in the flags section not only syn is set to 1 also NS and Reserved. what i want is to only set syn to 1 and the rest are 0

**Comment by fredericopissarra** [comment]
This is probably someting Linux puts it back... The reserved bits on tcphdr are all set to 1 accordingly to TCP_RESERVED_BITS constant on linux/tcp.h header definition.

You can change the line: tcp->res1 = 0 on modules/tcp.c and let me know what happens...

**Comment by azizhamad** [comment]
Thank you for your replay,
Your kind suggestion works fine, i can see now that NS and Reserved are set to 0.
