### ISSUE TITLE
Sign tar.gz packages

### ISSUE THREAD

**Issue by MarcosFouces** [fredericopissarra/t50#28]
Hello Frederico

Could you sign the tar.gz and release the *asc file with it? You can check an example here:
https://github.com/takaswie/libhinawa/releases

**Comment by fredericopissarra** [comment]
I believe all releases are signed, so are the commits, as shown below...

![signed](https://user-images.githubusercontent.com/6617952/39268081-2cae44b8-48a5-11e8-8644-719b08269483.png)

**Comment by fredericopissarra** [comment]
In the next release I'll include the sign.asc file with it...

**Comment by fredericopissarra** [comment]
Ok... t50-5.7.1.tar.gz.asc added to the last release!
