### ISSUE TITLE
Ability to flood server via MAC address

### ISSUE THREAD

**Issue by pavel-odintsov** [fredericopissarra/t50#9]
Hello!

I do some performance testing and need ability to flood to machine without specific IP directly by MAC. Is it possible?

**Comment by fredericopissarra** [comment]
Unfortunately, no. It's not possible.
The ability to use MAC addresses and to construct packets at ethernet level are features that I am thinking about. But there are other, more pressing, matters... The ability to use IPv6, for instance...
